- name: Deploy Application using Docker
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture_stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release_codename_stdout }} stable"
        filename: docker.list
        state: present
        update_cache: yes
      vars:
        dpkg_architecture_stdout: "{{ lookup('pipe', 'dpkg --print-architecture') }}"
        lsb_release_codename_stdout: "{{ lookup('pipe', 'lsb_release -cs') }}"
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start and enable Docker service
      service:
        name: docker
        enabled: yes
        state: started

    - name: Copy Dockerfile to server
      copy:
        src: Dockerfile
        dest: /home/ubuntu/Dockerfile

    - name: Copy JAR file to server
      copy:
        src: target
        dest: /home/ubuntu

    - name: Build Docker image
      command: docker build -t sarus23/medicure-app:1.0 .

    - name: Run Docker container
      command: docker run -d -p 8084:8084 sarus23/medicure-app:1.0
