apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-app
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-app
        image: sarus23/medicure-app:1.0
        ports:
      - containerPort: 8084
