---
- name: Install OpenJDK 11 and ChromeDriver on Ubuntu AWS
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install openjdk-11-jdk package
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install unzip package
      apt:
        name: unzip
        state: present

    - name: Install Google Chrome repository signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Update APT cache after adding repository
      apt:
        update_cache: yes

    - name: Install Google Chrome package
      apt:
        name: google-chrome-stable
        state: present

    - name: Download ChromeDriver zip
      get_url:
        url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
        dest: /tmp/chromedriver_version

    - name: Read ChromeDriver version from file
      slurp:
        src: /tmp/chromedriver_version
      register: chromedriver_version

    - name: Set ChromeDriver version variable
      set_fact:
        chromedriver_version: "{{ chromedriver_version['content'] | b64decode | string }}"

    - name: Download ChromeDriver
      unarchive:
        src: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
        dest: /tmp
        remote_src: yes
        creates: /tmp/chromedriver

    - name: Move ChromeDriver to /usr/local/bin
      command: "mv /tmp/chromedriver /usr/local/bin/"
