- name: Install OpenJDK 11, Chrome 116, and ChromeDriver 116 on Ubuntu AWS
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install openjdk-11-jdk package
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install unzip package
      apt:
        name: unzip
        state: present

    - name: Install Google Chrome repository signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Update APT cache after adding repository
      apt:
        update_cache: yes

    - name: get google chrome zip
      command: wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chrome-linux64.zip
      args:
        chdir: /tmp

    - name: unzip Google Chrome
      become: yes
      shell: "unzip -o /tmp/chrome-linux64.zip -d /opt"

    - name: Download ChromeDriver version 116
      get_url:
        url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
        dest: /tmp/chromedriver_linux64.zip

    - name: Unzip ChromeDriver
      unarchive:
        src: /tmp/chromedriver_linux64.zip
        dest: /tmp/
        remote_src: yes
        creates: /tmp/chromedriver

    - name: Change permissions and move ChromeDriver to /usr/local/bin
      become: yes
      shell: |
        chmod +x /tmp/chromedriver
        mv /tmp/chromedriver /usr/local/bin/
