---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update APT cache
      become: yes
      apt:
        update_cache: yes

    - name: Install openjdk-11-jdk package
      become: yes
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install zip tool
      become: yes
      apt:
        name: zip
        state: present
    
    - name: Install Google Chrome repository signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Update APT cache after adding repository
      apt:
        update_cache: yes

    - name: Remove Google Chrome
      apt:
        name: google-chrome-stable
        state: absent

    - name: Remove ChromeDriver
      become: yes
      file:
        path: /usr/bin/chromedriver
        state: absent

    - name: Download Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable.deb

    - name: Install Google Chrome package
      apt:
        deb: /tmp/google-chrome-stable.deb
        state: present

    - name: Download ChromeDriver
      get_url:
        url: https://chromedriver.storage.googleapis.com/116.0.5845.36/chromedriver_linux64.zip
        dest: /tmp/chromedriver-linux64.zip

    - name: Unzip ChromeDriver
      become: yes
      unarchive:
        src: /tmp/chromedriver-linux64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: Change ownership and permissions of ChromeDriver
      become: yes
      file:
        path: /usr/local/bin/chromedriver
        owner: root
        group: root
        mode: '0755'

    - name: Remove downloaded files
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/google-chrome-stable.deb
        - /tmp/chromedriver-linux64.zip
